version: "3.8"
services:
    # image project
    j0316dev:
        build: 
            args: 
                user: jo316dev
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - j0316dev
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8989:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - j0316dev

    # db pgsql
    pgsql:
        image: postgres
        restart: unless-stopped
        environment: 
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes: 
            - ./.pgsql/dbdata:/var/lib/postgresql
        ports: 
            - '5432:5432'
        networks: 
            - j0316dev

networks: 
    j0316dev:
        driver: bridge